## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class org.pytorch.** { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class com.facebook.** {*;}
-keep class java.util.Timer { *; }
-keep class java.util.TimerTask { *; }
-dontwarn io.flutter.embedding.**
